### ISSUE TITLE
Can't create shop and can't change marketplace listing ID after initial setup

### ISSUE THREAD

**Issue by manfromtunis** [OriginProtocol/dshop#1005]
Hello, 

I just set up the image on AWS following this tutorial : 
https://github.com/OriginProtocol/dshop/blob/master/docs/dshop/deployment/aws.md

When arriving at the first configuration step in the instance. 
I didn't know what information to put in the fields as no tutorial covered this, and the only configuration details i found are about localhost settings. 
So i set up marketplace listing ID as told in this page : 
![image](https://user-images.githubusercontent.com/50712247/138327897-4ffdf821-6c87-4dbd-847e-8d380151fe53.png)
But when i arrive at this and click on "create a shop" 
![image](https://user-images.githubusercontent.com/50712247/138327983-ea121886-d7a0-48f5-8425-9e8f434b7e52.png)

This error comes : 
![image](https://user-images.githubusercontent.com/50712247/138328023-46f3a7ce-b106-445d-a607-b47a922ce2cc.png)

So i don't know how to correct that, and how do i find the correct listing ID or even if i find it, how to change the configuration. 

so please any help on that is very welcome :)

**Comment by CRPTcuan** [comment]
![Captura de Pantalla 2021-10-29 a la(s) 21 22 09](https://user-images.githubusercontent.com/86898526/139513597-508f1778-ad97-4ee2-b05c-c047db0f422c.png)
![Captura de Pantalla 2021-10-29 a la(s) 21 21 24](https://user-images.githubusercontent.com/86898526/139513599-ee68d40e-f27d-43ec-8dd2-5986920131ab.png)
![Captura de Pantalla 2021-10-29 a la(s) 21 21 58](https://user-images.githubusercontent.com/86898526/139513601-f3a48dc9-5133-469d-a9bc-e49fdb164c58.png)
![Captura de Pantalla 2021-10-29 a la(s) 21 21 50](https://user-images.githubusercontent.com/86898526/139513602-6b9e526a-5800-4ea3-92aa-151f81776d53.png)

**Comment by CRPTcuan** [comment]
I would appreciate any kind of help ... thank you very much

**Comment by phyninja** [comment]
From [this blog](https://www.stackhawk.com/blog/fixing-no-access-control-allow-origin-header-present/) , I learned some of the technical details behind the error `No 'Access-Control-Allow-Origin' header is present on the requested resource`. According to the author, modern-day web browsers will first ask the "requested resource" whether it has any policies with respect to requests it will tend to before submitting the same to the resource. In our case, a conversation between the browser and the IPFS API server may go like this:

*You make a "request" to add some data to the IPFS API server by clicking on the 'Pay' button*
**Browser**: Hey, I have a request to make, but first, can you tell me if you have any conditions regarding whom you will accept requests from? 
**IPFS API Server**:  Yes, I will only accept requests coming from the same domain as me (ogn.app). 

The browser will then study your request to check whether it meets the server's policy. If it doesn't, it will revert back to you with the error above before even submitting the [payment] information to the server. It is for this reason that the Gateway server exists. A Gateway server is named as such because it acts as **gate** between the external world and the server that it houses. Notice how the IPFS Gateway has the same domain as the IPFS API server; to me, this says that IPFS API will accept requests coming from the Gateway server. 

Lately, people have been experiencing [issues with the IPFS Gateway server](https://discord.com/channels/404673842007506945/809309667398385694/903467814898266175) `https://fs-autossl.ogn.app`. I therefore recommend that you change the IPFS Gateway and API to a different domain (Ex. [Infura](https://infura.io/docs/ipfs)), publish your DShop, and then restart your GCP instance. Your Networks page will take on these changes if you choose to go with Infura:
`IPFS Gateway`: https://ipfs.infura.io/
`IPFS Server`: https://ipfs.infura.io:5001/

**Comment by CRPTcuan** [comment]
Hi .. if I had responded in the other thread .. it worked perfect ,, thank you very much that was it .. and I made an account in infura because they give 5 gigs for ipfs

thank you :)

**Comment by phyninja** [comment]
@manfromtunis 
W.r.t setting up your shop, how are things?

**Comment by GhassenMedyouni** [comment]
Hi @phyninja , I would like to know if you can help me with this problem .. I can't publish the changes to make the shop publicly visible, it always show me this message.
![Screenshot from 2021-11-19 02-54-59](https://user-images.githubusercontent.com/53530531/142551847-9fa569f7-a6f5-407d-bae7-5ab49f5e47d9.png)

**Comment by phyninja** [comment]
@GhassenMedyouni, let us work together in a new thread; the issue you're experiencing seems unrelated to the topic of this one. 

@manfromtunis I request that you re-open this thread if you're still facing the same issue.

**Comment by manfromtunis** [comment]
Hello @phyninja Thank you for your help, we managed to get through this problem. In fact @GhassenMedyouni and i works together. So new problems is good news :D. We'll documents the new problems we're facing in a new thread as you said. 

Thank you again !
