### ISSUE TITLE
Improve back-end resilience by using queues

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#16]
We should add a DB backed queue for listener tasks that are business critical. In particular for the following:
- creation of offers for credit card payments.
- acceptance of offers

The queueing framework should be relatively generic so that we can use it for any type of tasks in the future.

**Comment by DanielVF** [comment]
Orders are currently created in (_makeOffer.js)[https://github.com/OriginProtocol/dshop/blob/master/routes/_makeOffer.js] and immediately sent to the blockchain.

This is currently a problem, since two simultaneous orders will get the same tx ID going to the blockchain, and one will be lost.

The majority of the order work is done in in [handleLog.js](https://github.com/OriginProtocol/dshop/blob/1f35011e84c235de080deb69f4588d38153becbc/utils/handleLog.js). HandleLog is called by both the ongoing [listener.js,](https://github.com/OriginProtocol/dshop/blob/1f35011e84c235de080deb69f4588d38153becbc/listener.js) and by the [backfill.js](https://github.com/OriginProtocol/dshop/blob/6bb30af917ec6f9045c0b7da7eaad88f8c9e804d/scripts/backfill.js).

handleLog does:

- Upsert a new event in the database (_could uncle blocks mean the same TX is recorded and processed twice_)?
- Read from that db event
- Skip if not an offer
- Get the encrypted offer via IPFS
- Decrypt data via much magic
- Upsert the order in the DB
- Send an email
- Send a discord webhook

Orders are manually submitted to printful by a human.

**Comment by DanielVF** [comment]
![image](https://user-images.githubusercontent.com/837/81729955-d6cdcb00-945a-11ea-89c4-81b8b05697fe.png)

**Comment by franckc** [comment]
Great diagram :)
It helps a lot to visualize the data flow.

**Comment by DanielVF** [comment]
I've tested out a faked version of our system using both [bull](https://github.com/OptimalBits/bull/) and a quick, 30 minute, hand-rolled queue. 

My secret weapon, called one or two times from each action: 

```
randomFailure = (str) => {
    if(Math.random() < 0.30){
        throw(Error(str))
    }
}
```

Looks like bull will do a great job, and we won't need anything beyond it for the current set of needs. 

Unfortunately, ioredis-mock, does not support enough features to run bull. I've stubbed out the the one crashing missing calls, but something else is silently failing, or not being called, and no jobs go through. Looks like redis will have to be a dependency, but as dependencies go, that's not that bad.

I'm going to start with the Stripe webhook / OfferCreation queue.

**Comment by nick** [comment]
@DanielVF did you try [`redis-mock`](https://github.com/yeahoffline/redis-mock) instead of `ioredis-mock`?

**Comment by mikeshultz** [comment]
I've never been a fan of bull, but if y'all want to use it then so be it.  That said, building a DB queue would be relatively trivial.

**Comment by franckc** [comment]
Yeah I hear you @mikeshultz... @DanielVF did you weigh the pros/cons of using Bull vs building ourselves a super basic work queue backed by a db table?

**Comment by DanielVF** [comment]
@nick According to the someone far down in a github issue, redis-mock can work with bit of shims thrown in. I tested their code, and it doesn't work - it silently just lets bull use actual redis behind the scenes.

@franckc Yes, I initially leaned towards building our own DB backed queue. However, it looks like bull has good thought put into the error handling side, and an almost perfect API for what we are doing. I think this will save us bugs on the queue side vs writing our own.

**Comment by nick** [comment]
This has been done now.
