### ISSUE TITLE
Multiple 'rest of world' shipping options not working

### ISSUE THREAD

**Issue by nick** [OriginProtocol/dshop#267]
The user will only be presented with one of the 'rest of world' options on the frontend checkout

**Comment by phyninja** [comment]
Hi @nick,

What I've learned so far is that when a shop admin saves a form under Admin > Settings > Shipping with the 'Rest of the world' option set, a shipping.json file is generated/updated on the backend. For example:

```
[
  {
    "countries": [
      "US"
    ],
    "label": "",
    "processingTime": "",
    "detail": "",
    "amount": 0,
    "rates": [
      {
        "type": "free",
        "amount": 0
      },
      {
        "type": "fast",
        "amount": 1000
      }
    ]
  },
  {
    "label": "Free Shipping",
    "detail": "Arrives in 10 to 14 days",
    "amount": 0,
    "rates": [
      {
        "type": "slow",
        "amount": 2000
      },
      {
        "type": "fast",
        "amount": 4000
      },
      {
        "type": "expedited",
        "amount": 8000
      }
    ]
  },
  {
    "countries": [
      "AF"
    ],
    "label": "",
    "processingTime": "",
    "detail": "",
    "amount": 0,
    "rates": [
      {
        "type": "free",
        "amount": 0
      },
      {
        "type": "slow",
        "amount": 2000
      },
      {
        "type": "fast",
        "amount": 4000
      }
    ]
  }
]
```
In this example, the middle element refers to 'Rest of the world'. Given that the key `countries` is not populated here, I'm considering updating a file under https://github.com/OriginProtocol/dshop/tree/master/shop/src/pages/admin/settings/shipping to hopefully fix this issue. Would you please leave a comment if you believe the source of the issue lies elsewhere?

**Comment by phyninja** [comment]
Hi again @nick, 
I'm cc'ing @shahthepro because according to Github, they share authorship of the file https://github.com/OriginProtocol/dshop/blob/master/shop/src/pages/admin/settings/shipping/Edit.js with you. 

In looking at this issue from the point of view described above, I suggest editing the [`onChange` prop](https://github.com/OriginProtocol/dshop/blob/9c21cb9797d33f691bf19efc7f474fff4ee45bfa/shop/src/pages/admin/settings/shipping/Edit.js#L395) of the above file to make the fields in shipping.json consistent. Particularly, when a shop is newly built, 
the contents of shipping.json is as follows:
```
[
  {
    "id": "international",
    "label": "Free Shipping",
    "detail": "Arrives in 10 to 14 days",
    "amount": 0
  }
]
```
Correct me if I'm wrong, but as I understand, when an Admin updates the Shipping settings for the first time, the "source country" object is moved to the top. If they choose to add a second destination, the details of that are [combined](https://github.com/OriginProtocol/dshop/blob/9c21cb9797d33f691bf19efc7f474fff4ee45bfa/shop/src/pages/admin/settings/shipping/Edit.js#L395) into the object above.
The result here is a JSON file whose contents may look like: 
```
[
  {
    "countries": [
      "US"
    ],
    "label": "",
    "processingTime": "",
    "detail": "",
    "amount": 0,
    "rates": [
      {
        "type": "free",
        "amount": 0
      },
      {
        "type": "expedited",
        "amount": 2000
      }
    ]
  },
  {
    "countries": [
      "AX"
    ],
    "label": "Free Shipping",
    "detail": "Arrives in 10 to 14 days",
    "amount": 0,
    "rates": [
      {
        "type": "fast",
        "amount": 4000
      },
      {
        "type": "slow",
        "amount": 2000
      }
    ]
  }
]
```
From my testing, I saw that the fields 
```
    "label": "Free Shipping",
    "detail": "Arrives in 10 to 14 days",
```
are displayed during checkout only when the shop is new, and shipping settings are not yet configured by the Admin.
