### ISSUE TITLE
Wallet not successfully connected to Dshop account regression

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/dshop#270]
On another round of testing I have run into an issue where the crypto wallet did not connect properly after the transaction was mined.

It's not a state issue as I have refreshed the page multiple times.
 
<img width="1904" alt="Screen Shot 2020-07-17 at 5 37 44 PM" src="https://user-images.githubusercontent.com/4960567/87840559-22cf2e80-c855-11ea-8575-c5f93e4f8734.png">

**Comment by matthewliu** [comment]
A second transaction fixed this, so I'm not sure what caused the first failure.

**Comment by nick** [comment]
I think this is due to you having to remain on the page until the transaction is mined in order for the DB to be updated. Instead, we should send the TX hash to the backend so that the listener can wait for it to be mined and then update the database. This would allow users to leave the page or speed up the transaction without interrupting the database update.

**Comment by matthewliu** [comment]
Yea that explains it. I did leave the page after awhile. Didn't realize that that would prevent the database update.

**Comment by nick** [comment]
Closing this as it's tracked in #345
