### ISSUE TITLE
Verifying custom domain does not consistently return the same result

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#390]
I added a custom domain www.dshoptest.com to my store anna-test-16.ogn.app and clicked "verify" multiple times. The feedback alternated between "your changes haven't propagated" and "looks good".

See video [here](https://www.loom.com/share/e87dc22813ce4102a059feafe3f3178b)

**Comment by mikeshultz** [comment]
This is due to the IPFS servers' pod polling the kubernetes DNS source which is ultimately Google's DNS servers(`8.8.8.8` and `8.8.4.4`).  Their massive cluster of DNS servers may not always agree immediately so there may be a delay where this can happen.  Also, where one request to IPFS might succeed and a subsequent one may return a 404(failed IPNS resolution).

We can smooth this out a bit by using a single DNS source or a couple closely linked DNS server pods of our own.
