### ISSUE TITLE
Successful transaction not showing up in Orders 

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#554]
A buyer successfully purchased an item from della-chelpka-art.ogn.app and the payment was successful as well (shows up in the seller's Stripe account). However there are no new orders reflected in Dshop admin > Orders.

**Comment by gullible1** [comment]
Similar issue reported on pundi-x.ogn.app. Payment made by credit card as well. An order confirmation email was sent out but no new order was shown in Orders on the Dshop admin.

**Comment by franckc** [comment]
This should now be fixed after we ran a script last night for migrating old orders to the new schema. Please re-open if it is still happening.

**Comment by christopherchelpka** [comment]
> This should now be fixed after we ran a script last night for migrating old orders to the new schema. Please re-open if it is still happening.

I've signed out and signed in and there is still no record of any orders in the Dshop admin.

**Comment by franckc** [comment]
Double checked and while orders are showing up in the Pundi store, they don't on the della-chelpka-art store (shopId 185).
We need to investigate that one... Re-opening this issue.

**Comment by gullible1** [comment]
@shahthepro @franckc ybmstore.ogn.app just reported that an order is not showing up on his store either. This order was paid for via Paypal and the merchant received a confirmation email from Paypal (see screenshot below), but the order didn't show up on his Dshop admin. 

<img width="1087" alt="Screenshot 2020-09-24 at 11 10 15 PM" src="https://user-images.githubusercontent.com/46481405/94164251-61b7db00-febb-11ea-9fbb-c5f27026ea0e.png">

**Comment by franckc** [comment]
Regarding the Della Chelpka store, I noticed the PGP private key is missing under Settings > Server.
<img width="1194" alt="Screen Shot 2020-09-24 at 3 40 14 PM" src="https://user-images.githubusercontent.com/945910/94207433-7923a380-fe7c-11ea-8971-5a9c5e29924a.png">

This is preventing the back-end from processing any order for that shop since it is unable to decrypt the data.

So far a single order is impacted:
 - created at 2020-09-22 20:45:44 UTC
 - tx hash 0x2a4706b173946a44c41eed1778789ead8e8da772a68b66f436f7eaf697568884

@christopherchelpka do you have by any chance a copy of the PGP private key? If not, we can generate a new one for you and re-publish your store but then unfortunately we will not be able to process the failed order :(

**Comment by christopherchelpka** [comment]
@franckc good catch. But I do not remember receiving or setting up a PGP private key and don't one see in my password manager. Also, FWIW, I do not see a server option under the settings menu, but I was able to access the page by adjusting the url.

Bottomline: I think you'll need generate a new key and re-publish.

**Comment by franckc** [comment]
@gullible1 It would be really helpful to get more details on the specific credit card payments that failed for Pundit and ybmstore. Could they provide us with a screenshot of the payment details page for each failed payment? Or alternatively if they could send us the "Payment method ID" that shows on the Stripe payment details page so that we can look it up on our end. Thanks!

**Comment by franckc** [comment]
Regarding the PayPal payment to YMG with ID 6Y86141MF834723T, we got the webhook call from paypal to notify us it was pending. We can see that with this query:
```
select * from external_payments where external_id='WH-50313618UL809412W-96B4488438415890G';
```
Now, we don't create an order on our side for those pending paypal payments, that's why it does not show up yet in the merchant's orders. Once PayPal calls our webhook to let us know the echeck cleared, the order should show up.
This can be confusing for merchants so I'm going to create a separate issue for us to create an order with payment_status "pending" in this case.

**Comment by franckc** [comment]
@christopherchelpka We regenerated PGP encryption keys for you and re-published your awesome art store on your behalf. You should now be all good to go :) Sorry about the inconvenience!

CC @gullible1

**Comment by shahthepro** [comment]
Franck has fixed this already. Closing this
