### ISSUE TITLE
Printful auto-fulfilment not working

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#560]
Orders made on Dshops integrated with Printful are not being pushed automatically to Printful despite checking the "auto-fulfil" box when sync-ing Printful.

Some stores experiencing these include pundi-x.ogn.app and della-chelpka-art.ogn.app.

Orders should be pushed to Printful upon a successful payment, except in the event of a manual payment, in which the merchant should be able to check that they've received payment then mark the order as paid, before having it fulfilled by Printful.

**Comment by franckc** [comment]
Looking at back-end logs, I see entries like this:
```
[ERROR] dshop.routes.printful: Invalid secret, ignoring event { sync_product:
```
This originates from this line in the code https://github.com/OriginProtocol/dshop/blob/master/backend/routes/printful.js#L75

Unfortunately, for some reason I don't understand, the data gets chopped when it gets logged...

**Comment by franckc** [comment]
Those error above are not related to this issue I think.

I think the reason orders are not auto-fulfilled on Printful for Pundit and Della-Chelpka is because those merchants did not opt in for auto-fulfilling orders when hey configured Printful.

To set this option, go to admin, Apps > Settings > Printful and click on "Configure". Then check "Auto-fulfill orders".

<img width="502" alt="Screen Shot 2020-09-23 at 12 55 04 PM" src="https://user-images.githubusercontent.com/945910/94062934-338fa980-fd9c-11ea-91a2-a8deab619836.png">

@gullible1 Can you ask them to update their config and try again?

**Comment by christopherchelpka** [comment]
I'm the admin for della-chelpka-art.org.app and I appreciate your quick response. You are correct that the "auto-fulfill orders" box was not checked. It's checked now. 

Is this also the solution for [Stripe-processed orders not showing up in the Dshop admin panel](https://github.com/OriginProtocol/dshop/issues/554)?

**Comment by franckc** [comment]
@gullible1 I'm going to close this since this does not seem to be a bug. Please re-open if you know of a shop that still has auto-fulfillment issue despite having it enabled in their settings
