### ISSUE TITLE
Order stuck on "processing" and can't be completed

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#592]
A buyer is trying to make a purchase from [della-chelpka-art.ogn.app](url) and his store is experiencing issues again, this time the order won't process at all and the buyer sees the "it looks like we are having issues" error. 

When attempting to place the order, the page is stuck on "processing". No order shows up in the Dshop admin or in Stripe.

Console screenshot from @shahthepro , who was able to reproduce the error.

<img width="447" alt="Screenshot_2020-10-01_at_9 21 25_AM" src="https://user-images.githubusercontent.com/46481405/94799854-5f530500-0416-11eb-9398-69f8a46bdca6.png">

Might be unrelated, but the same buyer had run into issues placing an order on the same store: https://github.com/OriginProtocol/dshop/issues/554

**Comment by franckc** [comment]
We had an IPFS outage due to a server disk full.

Thanks to @mikeshultz, once we diagnosed the issue we fixed it promptly.

We'll work on improving our devops procedures so that we don't run into a similar problem again.

Tested in prod and was able to place an order. All shops should now be functioning normally.
Closing this bug.
