### ISSUE TITLE
annasfiestas.ogn.app stuck on login screen

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#763]
https://annasfiestas.ogn.app brings me to the Dshop login page instead of my shopfront. Entering my log in credentials doesn't work either.

Can't seem to find another store with the same issue.

Not sure if it is related, but I'd previously changed my shop name and my old .ogn.app domain was annas-fiestas.ogn.app, which is currently still working.

**Comment by mikeshultz** [comment]
So, the node domain hostname for the shops(e.g. `annasfiestas.ogn.app`) that is displayed in the UI is derived by the `shop.hostname` field in the DB mashed up against `network.domain`.

The backend is currently making its decision on which shop to deploy using the table `shop_domains`.  So, when the name was updated, the `hostname` was updated, but the serving logic doesn't care. 

And the only reason `annas-fiestas.ogn.app` still works is because of the cache.  I expect that next restart or deployment will wipe that and the shop won't load at all.

Short term I'll update the backend to also check against `shop.hostname` + `network.config.domain` but that seems a little redundant to me.  We should either not have node-domain hostnames in shop_domains or only have them there.

**Comment by mikeshultz** [comment]
That PR apparently did not fix this...  looking...

**Comment by mikeshultz** [comment]
Fixed the fix in 15378800889323056d06e4e97a86d49711769ec7
