### ISSUE TITLE
Mobile checkout error

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#933]
Looks like there's an error when trying to step through the checkout process.  This was noticed on https://store.originprotocol.com/.

On mobile, if you fill out your name and number and tap "Continue", nothing happens.  I haven't been able to look for console errors yet.

This was originally reported on Safari Mobile, and I was able to repro on Firefox Mobile (android).

**Comment by etnlbck** [comment]
I was also able to repro Chrome iOS.

**Comment by etnlbck** [comment]
@mikeshultz The bug has to do with how `form` validations are handled. 

On mobile, `Continue` should take the user to step 2, but appears to stick.
Since all of `state` gets validated when `onSubmit` is fired, the shipping fields aren't on the DOM causing the form to be invalid.

**Proposed Solution:**
If a user is on mobile, validate the `email` field then display shipping info fields. 
`shop/src/pages/checkout/Information.js`

**Comment by etnlbck** [comment]
This issue can be closed.
